### ISSUE TITLE
Copy image file

### ISSUE THREAD

**Issue by choonho** [Cvr421/myplugin#1]
I think you missed copy image file in Dockerfile.

**Comment by Cvr421** [comment]
Hello @choonho i  have added the image file into docker file please review 
Is this correct 
https://github.com/Cvr421/myplugin/blob/main/Dockerfile
# Dockerfile
FROM nginx:latest
COPY flying-wonny_christmas-version.png /usr/share/nginx/html/flying-wonny_christmas-version.png
COPY index.html /usr/share/nginx/html/index.html

**Comment by choonho** [comment]
> https://github.com/Cvr421/myplugin/blob/main/Dockerfile

@Cvr421 LGTM
